<?php
    $Payer_AgentId="YOUR_AGENT_ID";
    $Payer_Key1="YOUR_KEY_1";
    $Payer_Key2="YOUR_KEY_2";
    $Payer_RedirectPath="http://secure.payer.se/w3/payread.cgi";
    $Payer_Version="30";
    $PayRead_AgentId="YOUR_AGENT_ID";
    $PayRead_Key1="YOUR_KEY_1";
    $PayRead_Key2="YOUR_KEY_2";
    $PayRead_RedirectPath="http://secure.payer.se/w3/payread.cgi";
    $PayRead_Version="30";
?>